version: "3.9"

services:
  web:
    container_name: cs2inspect-web
    build:
      context: .
      dockerfile: Dockerfile
    image: cs2inspect-web:latest
    restart: unless-stopped
    environment:
      # Core
      - NODE_ENV=production
      - PORT=${PORT:-3000}
      - HOST=${HOST:-0.0.0.0}

      # JWT / Auth
      - JWT_TOKEN=${JWT_TOKEN}
      - JWT_EXPIRY=${JWT_EXPIRY}

      # Database (handled separately; only passing through connection envs)
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_CONNECTION_LIMIT=${DATABASE_CONNECTION_LIMIT}

      # Steam
      - STEAM_API_KEY=${STEAM_API_KEY}
      - STEAM_USERNAME=${STEAM_USERNAME}
      - STEAM_PASSWORD=${STEAM_PASSWORD}

      # Misc
      - LOG_API_REQUESTS=${LOG_API_REQUESTS}

    ports:
      # Map host:container ports, defaulting to 3000 if not set in Coolify
      - "${PORT:-3000}:${PORT:-3000}"

    # No database service here; Coolify manages DB separately

