/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NAlert: typeof import('naive-ui')['NAlert']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCheckboxGroup: typeof import('naive-ui')['NCheckboxGroup']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NH2: typeof import('naive-ui')['NH2']
    NH3: typeof import('naive-ui')['NH3']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NPagination: typeof import('naive-ui')['NPagination']
    NProgress: typeof import('naive-ui')['NProgress']
    NSelect: typeof import('naive-ui')['NSelect']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSlider: typeof import('naive-ui')['NSlider']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const NAlert: (typeof import('naive-ui'))['NAlert']
  const NCard: (typeof import('naive-ui'))['NCard']
  const NCheckbox: (typeof import('naive-ui'))['NCheckbox']
  const NCheckboxGroup: (typeof import('naive-ui'))['NCheckboxGroup']
  const NCollapse: (typeof import('naive-ui'))['NCollapse']
  const NCollapseItem: (typeof import('naive-ui'))['NCollapseItem']
  const NConfigProvider: (typeof import('naive-ui'))['NConfigProvider']
  const NDataTable: (typeof import('naive-ui'))['NDataTable']
  const NDialogProvider: (typeof import('naive-ui'))['NDialogProvider']
  const NDivider: (typeof import('naive-ui'))['NDivider']
  const NDrawer: (typeof import('naive-ui'))['NDrawer']
  const NDrawerContent: (typeof import('naive-ui'))['NDrawerContent']
  const NEmpty: (typeof import('naive-ui'))['NEmpty']
  const NH2: (typeof import('naive-ui'))['NH2']
  const NH3: (typeof import('naive-ui'))['NH3']
  const NIcon: (typeof import('naive-ui'))['NIcon']
  const NInput: (typeof import('naive-ui'))['NInput']
  const NInputGroup: (typeof import('naive-ui'))['NInputGroup']
  const NInputNumber: (typeof import('naive-ui'))['NInputNumber']
  const NLoadingBarProvider: (typeof import('naive-ui'))['NLoadingBarProvider']
  const NMenu: (typeof import('naive-ui'))['NMenu']
  const NMessageProvider: (typeof import('naive-ui'))['NMessageProvider']
  const NModal: (typeof import('naive-ui'))['NModal']
  const NModalProvider: (typeof import('naive-ui'))['NModalProvider']
  const NPagination: (typeof import('naive-ui'))['NPagination']
  const NProgress: (typeof import('naive-ui'))['NProgress']
  const NSelect: (typeof import('naive-ui'))['NSelect']
  const NSkeleton: (typeof import('naive-ui'))['NSkeleton']
  const NSlider: (typeof import('naive-ui'))['NSlider']
  const NSpace: (typeof import('naive-ui'))['NSpace']
  const NSpin: (typeof import('naive-ui'))['NSpin']
  const NSwitch: (typeof import('naive-ui'))['NSwitch']
  const NTabPane: (typeof import('naive-ui'))['NTabPane']
  const NTabs: (typeof import('naive-ui'))['NTabs']
  const NTag: (typeof import('naive-ui'))['NTag']
  const NText: (typeof import('naive-ui'))['NText']
  const NTooltip: (typeof import('naive-ui'))['NTooltip']
  const RouterLink: (typeof import('vue-router'))['RouterLink']
  const RouterView: (typeof import('vue-router'))['RouterView']
}
