-- Step 1: Add new JSON columns to all weapon tables
ALTER TABLE `wp_player_heavys` ADD COLUMN `sticker_0_new` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_heavys` ADD COLUMN `sticker_1_new` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_heavys` ADD COLUMN `sticker_2_new` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_heavys` ADD COLUMN `sticker_3_new` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_heavys` ADD COLUMN `sticker_4_new` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_heavys` ADD COLUMN `keychain_new` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_pistols` ADD COLUMN `sticker_0_new` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_pistols` ADD COLUMN `sticker_1_new` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_pistols` ADD COLUMN `sticker_2_new` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_pistols` ADD COLUMN `sticker_3_new` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_pistols` ADD COLUMN `sticker_4_new` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_pistols` ADD COLUMN `keychain_new` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_rifles` ADD COLUMN `sticker_0_new` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_rifles` ADD COLUMN `sticker_1_new` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_rifles` ADD COLUMN `sticker_2_new` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_rifles` ADD COLUMN `sticker_3_new` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_rifles` ADD COLUMN `sticker_4_new` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_rifles` ADD COLUMN `keychain_new` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_smgs` ADD COLUMN `sticker_0_new` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_smgs` ADD COLUMN `sticker_1_new` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_smgs` ADD COLUMN `sticker_2_new` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_smgs` ADD COLUMN `sticker_3_new` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_smgs` ADD COLUMN `sticker_4_new` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_smgs` ADD COLUMN `keychain_new` json DEFAULT NULL;--> statement-breakpoint

-- Step 2: Migrate sticker data (format: id;x;y;wear;scale;rotation -> JSON)
UPDATE `wp_player_heavys` SET `sticker_0_new` = IF(`sticker_0` = '0;0;0;0;0;0' OR `sticker_0` IS NULL OR CAST(SUBSTRING_INDEX(`sticker_0`, ';', 1) AS SIGNED) = 0, NULL, JSON_OBJECT('id', CAST(SUBSTRING_INDEX(`sticker_0`, ';', 1) AS SIGNED), 'x', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_0`, ';', 2), ';', -1) AS DOUBLE), 'y', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_0`, ';', 3), ';', -1) AS DOUBLE), 'wear', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_0`, ';', 4), ';', -1) AS DOUBLE), 'scale', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_0`, ';', 5), ';', -1) AS DOUBLE), 'rotation', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_0`, ';', 6), ';', -1) AS SIGNED)));--> statement-breakpoint
UPDATE `wp_player_heavys` SET `sticker_1_new` = IF(`sticker_1` = '0;0;0;0;0;0' OR `sticker_1` IS NULL OR CAST(SUBSTRING_INDEX(`sticker_1`, ';', 1) AS SIGNED) = 0, NULL, JSON_OBJECT('id', CAST(SUBSTRING_INDEX(`sticker_1`, ';', 1) AS SIGNED), 'x', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_1`, ';', 2), ';', -1) AS DOUBLE), 'y', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_1`, ';', 3), ';', -1) AS DOUBLE), 'wear', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_1`, ';', 4), ';', -1) AS DOUBLE), 'scale', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_1`, ';', 5), ';', -1) AS DOUBLE), 'rotation', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_1`, ';', 6), ';', -1) AS SIGNED)));--> statement-breakpoint
UPDATE `wp_player_heavys` SET `sticker_2_new` = IF(`sticker_2` = '0;0;0;0;0;0' OR `sticker_2` IS NULL OR CAST(SUBSTRING_INDEX(`sticker_2`, ';', 1) AS SIGNED) = 0, NULL, JSON_OBJECT('id', CAST(SUBSTRING_INDEX(`sticker_2`, ';', 1) AS SIGNED), 'x', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_2`, ';', 2), ';', -1) AS DOUBLE), 'y', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_2`, ';', 3), ';', -1) AS DOUBLE), 'wear', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_2`, ';', 4), ';', -1) AS DOUBLE), 'scale', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_2`, ';', 5), ';', -1) AS DOUBLE), 'rotation', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_2`, ';', 6), ';', -1) AS SIGNED)));--> statement-breakpoint
UPDATE `wp_player_heavys` SET `sticker_3_new` = IF(`sticker_3` = '0;0;0;0;0;0' OR `sticker_3` IS NULL OR CAST(SUBSTRING_INDEX(`sticker_3`, ';', 1) AS SIGNED) = 0, NULL, JSON_OBJECT('id', CAST(SUBSTRING_INDEX(`sticker_3`, ';', 1) AS SIGNED), 'x', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_3`, ';', 2), ';', -1) AS DOUBLE), 'y', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_3`, ';', 3), ';', -1) AS DOUBLE), 'wear', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_3`, ';', 4), ';', -1) AS DOUBLE), 'scale', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_3`, ';', 5), ';', -1) AS DOUBLE), 'rotation', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_3`, ';', 6), ';', -1) AS SIGNED)));--> statement-breakpoint
UPDATE `wp_player_heavys` SET `sticker_4_new` = IF(`sticker_4` = '0;0;0;0;0;0' OR `sticker_4` IS NULL OR CAST(SUBSTRING_INDEX(`sticker_4`, ';', 1) AS SIGNED) = 0, NULL, JSON_OBJECT('id', CAST(SUBSTRING_INDEX(`sticker_4`, ';', 1) AS SIGNED), 'x', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_4`, ';', 2), ';', -1) AS DOUBLE), 'y', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_4`, ';', 3), ';', -1) AS DOUBLE), 'wear', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_4`, ';', 4), ';', -1) AS DOUBLE), 'scale', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_4`, ';', 5), ';', -1) AS DOUBLE), 'rotation', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_4`, ';', 6), ';', -1) AS SIGNED)));--> statement-breakpoint
UPDATE `wp_player_heavys` SET `keychain_new` = IF(`keychain` = '0;0;0;0;0' OR `keychain` IS NULL OR CAST(SUBSTRING_INDEX(`keychain`, ';', 1) AS SIGNED) = 0, NULL, JSON_OBJECT('id', CAST(SUBSTRING_INDEX(`keychain`, ';', 1) AS SIGNED), 'x', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`keychain`, ';', 2), ';', -1) AS DOUBLE), 'y', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`keychain`, ';', 3), ';', -1) AS DOUBLE), 'z', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`keychain`, ';', 4), ';', -1) AS DOUBLE), 'seed', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`keychain`, ';', 5), ';', -1) AS SIGNED), 'wrapped_sticker_id', `wrapped_sticker_id`, 'highlight_reel_id', `highlight_reel_id`));--> statement-breakpoint

UPDATE `wp_player_pistols` SET `sticker_0_new` = IF(`sticker_0` = '0;0;0;0;0;0' OR `sticker_0` IS NULL OR CAST(SUBSTRING_INDEX(`sticker_0`, ';', 1) AS SIGNED) = 0, NULL, JSON_OBJECT('id', CAST(SUBSTRING_INDEX(`sticker_0`, ';', 1) AS SIGNED), 'x', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_0`, ';', 2), ';', -1) AS DOUBLE), 'y', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_0`, ';', 3), ';', -1) AS DOUBLE), 'wear', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_0`, ';', 4), ';', -1) AS DOUBLE), 'scale', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_0`, ';', 5), ';', -1) AS DOUBLE), 'rotation', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_0`, ';', 6), ';', -1) AS SIGNED)));--> statement-breakpoint
UPDATE `wp_player_pistols` SET `sticker_1_new` = IF(`sticker_1` = '0;0;0;0;0;0' OR `sticker_1` IS NULL OR CAST(SUBSTRING_INDEX(`sticker_1`, ';', 1) AS SIGNED) = 0, NULL, JSON_OBJECT('id', CAST(SUBSTRING_INDEX(`sticker_1`, ';', 1) AS SIGNED), 'x', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_1`, ';', 2), ';', -1) AS DOUBLE), 'y', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_1`, ';', 3), ';', -1) AS DOUBLE), 'wear', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_1`, ';', 4), ';', -1) AS DOUBLE), 'scale', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_1`, ';', 5), ';', -1) AS DOUBLE), 'rotation', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_1`, ';', 6), ';', -1) AS SIGNED)));--> statement-breakpoint
UPDATE `wp_player_pistols` SET `sticker_2_new` = IF(`sticker_2` = '0;0;0;0;0;0' OR `sticker_2` IS NULL OR CAST(SUBSTRING_INDEX(`sticker_2`, ';', 1) AS SIGNED) = 0, NULL, JSON_OBJECT('id', CAST(SUBSTRING_INDEX(`sticker_2`, ';', 1) AS SIGNED), 'x', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_2`, ';', 2), ';', -1) AS DOUBLE), 'y', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_2`, ';', 3), ';', -1) AS DOUBLE), 'wear', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_2`, ';', 4), ';', -1) AS DOUBLE), 'scale', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_2`, ';', 5), ';', -1) AS DOUBLE), 'rotation', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_2`, ';', 6), ';', -1) AS SIGNED)));--> statement-breakpoint
UPDATE `wp_player_pistols` SET `sticker_3_new` = IF(`sticker_3` = '0;0;0;0;0;0' OR `sticker_3` IS NULL OR CAST(SUBSTRING_INDEX(`sticker_3`, ';', 1) AS SIGNED) = 0, NULL, JSON_OBJECT('id', CAST(SUBSTRING_INDEX(`sticker_3`, ';', 1) AS SIGNED), 'x', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_3`, ';', 2), ';', -1) AS DOUBLE), 'y', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_3`, ';', 3), ';', -1) AS DOUBLE), 'wear', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_3`, ';', 4), ';', -1) AS DOUBLE), 'scale', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_3`, ';', 5), ';', -1) AS DOUBLE), 'rotation', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_3`, ';', 6), ';', -1) AS SIGNED)));--> statement-breakpoint
UPDATE `wp_player_pistols` SET `sticker_4_new` = IF(`sticker_4` = '0;0;0;0;0;0' OR `sticker_4` IS NULL OR CAST(SUBSTRING_INDEX(`sticker_4`, ';', 1) AS SIGNED) = 0, NULL, JSON_OBJECT('id', CAST(SUBSTRING_INDEX(`sticker_4`, ';', 1) AS SIGNED), 'x', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_4`, ';', 2), ';', -1) AS DOUBLE), 'y', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_4`, ';', 3), ';', -1) AS DOUBLE), 'wear', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_4`, ';', 4), ';', -1) AS DOUBLE), 'scale', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_4`, ';', 5), ';', -1) AS DOUBLE), 'rotation', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_4`, ';', 6), ';', -1) AS SIGNED)));--> statement-breakpoint
UPDATE `wp_player_pistols` SET `keychain_new` = IF(`keychain` = '0;0;0;0;0' OR `keychain` IS NULL OR CAST(SUBSTRING_INDEX(`keychain`, ';', 1) AS SIGNED) = 0, NULL, JSON_OBJECT('id', CAST(SUBSTRING_INDEX(`keychain`, ';', 1) AS SIGNED), 'x', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`keychain`, ';', 2), ';', -1) AS DOUBLE), 'y', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`keychain`, ';', 3), ';', -1) AS DOUBLE), 'z', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`keychain`, ';', 4), ';', -1) AS DOUBLE), 'seed', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`keychain`, ';', 5), ';', -1) AS SIGNED), 'wrapped_sticker_id', `wrapped_sticker_id`, 'highlight_reel_id', `highlight_reel_id`));--> statement-breakpoint

UPDATE `wp_player_rifles` SET `sticker_0_new` = IF(`sticker_0` = '0;0;0;0;0;0' OR `sticker_0` IS NULL OR CAST(SUBSTRING_INDEX(`sticker_0`, ';', 1) AS SIGNED) = 0, NULL, JSON_OBJECT('id', CAST(SUBSTRING_INDEX(`sticker_0`, ';', 1) AS SIGNED), 'x', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_0`, ';', 2), ';', -1) AS DOUBLE), 'y', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_0`, ';', 3), ';', -1) AS DOUBLE), 'wear', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_0`, ';', 4), ';', -1) AS DOUBLE), 'scale', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_0`, ';', 5), ';', -1) AS DOUBLE), 'rotation', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_0`, ';', 6), ';', -1) AS SIGNED)));--> statement-breakpoint
UPDATE `wp_player_rifles` SET `sticker_1_new` = IF(`sticker_1` = '0;0;0;0;0;0' OR `sticker_1` IS NULL OR CAST(SUBSTRING_INDEX(`sticker_1`, ';', 1) AS SIGNED) = 0, NULL, JSON_OBJECT('id', CAST(SUBSTRING_INDEX(`sticker_1`, ';', 1) AS SIGNED), 'x', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_1`, ';', 2), ';', -1) AS DOUBLE), 'y', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_1`, ';', 3), ';', -1) AS DOUBLE), 'wear', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_1`, ';', 4), ';', -1) AS DOUBLE), 'scale', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_1`, ';', 5), ';', -1) AS DOUBLE), 'rotation', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_1`, ';', 6), ';', -1) AS SIGNED)));--> statement-breakpoint
UPDATE `wp_player_rifles` SET `sticker_2_new` = IF(`sticker_2` = '0;0;0;0;0;0' OR `sticker_2` IS NULL OR CAST(SUBSTRING_INDEX(`sticker_2`, ';', 1) AS SIGNED) = 0, NULL, JSON_OBJECT('id', CAST(SUBSTRING_INDEX(`sticker_2`, ';', 1) AS SIGNED), 'x', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_2`, ';', 2), ';', -1) AS DOUBLE), 'y', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_2`, ';', 3), ';', -1) AS DOUBLE), 'wear', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_2`, ';', 4), ';', -1) AS DOUBLE), 'scale', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_2`, ';', 5), ';', -1) AS DOUBLE), 'rotation', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_2`, ';', 6), ';', -1) AS SIGNED)));--> statement-breakpoint
UPDATE `wp_player_rifles` SET `sticker_3_new` = IF(`sticker_3` = '0;0;0;0;0;0' OR `sticker_3` IS NULL OR CAST(SUBSTRING_INDEX(`sticker_3`, ';', 1) AS SIGNED) = 0, NULL, JSON_OBJECT('id', CAST(SUBSTRING_INDEX(`sticker_3`, ';', 1) AS SIGNED), 'x', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_3`, ';', 2), ';', -1) AS DOUBLE), 'y', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_3`, ';', 3), ';', -1) AS DOUBLE), 'wear', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_3`, ';', 4), ';', -1) AS DOUBLE), 'scale', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_3`, ';', 5), ';', -1) AS DOUBLE), 'rotation', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_3`, ';', 6), ';', -1) AS SIGNED)));--> statement-breakpoint
UPDATE `wp_player_rifles` SET `sticker_4_new` = IF(`sticker_4` = '0;0;0;0;0;0' OR `sticker_4` IS NULL OR CAST(SUBSTRING_INDEX(`sticker_4`, ';', 1) AS SIGNED) = 0, NULL, JSON_OBJECT('id', CAST(SUBSTRING_INDEX(`sticker_4`, ';', 1) AS SIGNED), 'x', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_4`, ';', 2), ';', -1) AS DOUBLE), 'y', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_4`, ';', 3), ';', -1) AS DOUBLE), 'wear', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_4`, ';', 4), ';', -1) AS DOUBLE), 'scale', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_4`, ';', 5), ';', -1) AS DOUBLE), 'rotation', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_4`, ';', 6), ';', -1) AS SIGNED)));--> statement-breakpoint
UPDATE `wp_player_rifles` SET `keychain_new` = IF(`keychain` = '0;0;0;0;0' OR `keychain` IS NULL OR CAST(SUBSTRING_INDEX(`keychain`, ';', 1) AS SIGNED) = 0, NULL, JSON_OBJECT('id', CAST(SUBSTRING_INDEX(`keychain`, ';', 1) AS SIGNED), 'x', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`keychain`, ';', 2), ';', -1) AS DOUBLE), 'y', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`keychain`, ';', 3), ';', -1) AS DOUBLE), 'z', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`keychain`, ';', 4), ';', -1) AS DOUBLE), 'seed', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`keychain`, ';', 5), ';', -1) AS SIGNED), 'wrapped_sticker_id', `wrapped_sticker_id`, 'highlight_reel_id', `highlight_reel_id`));--> statement-breakpoint

UPDATE `wp_player_smgs` SET `sticker_0_new` = IF(`sticker_0` = '0;0;0;0;0;0' OR `sticker_0` IS NULL OR CAST(SUBSTRING_INDEX(`sticker_0`, ';', 1) AS SIGNED) = 0, NULL, JSON_OBJECT('id', CAST(SUBSTRING_INDEX(`sticker_0`, ';', 1) AS SIGNED), 'x', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_0`, ';', 2), ';', -1) AS DOUBLE), 'y', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_0`, ';', 3), ';', -1) AS DOUBLE), 'wear', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_0`, ';', 4), ';', -1) AS DOUBLE), 'scale', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_0`, ';', 5), ';', -1) AS DOUBLE), 'rotation', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_0`, ';', 6), ';', -1) AS SIGNED)));--> statement-breakpoint
UPDATE `wp_player_smgs` SET `sticker_1_new` = IF(`sticker_1` = '0;0;0;0;0;0' OR `sticker_1` IS NULL OR CAST(SUBSTRING_INDEX(`sticker_1`, ';', 1) AS SIGNED) = 0, NULL, JSON_OBJECT('id', CAST(SUBSTRING_INDEX(`sticker_1`, ';', 1) AS SIGNED), 'x', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_1`, ';', 2), ';', -1) AS DOUBLE), 'y', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_1`, ';', 3), ';', -1) AS DOUBLE), 'wear', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_1`, ';', 4), ';', -1) AS DOUBLE), 'scale', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_1`, ';', 5), ';', -1) AS DOUBLE), 'rotation', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_1`, ';', 6), ';', -1) AS SIGNED)));--> statement-breakpoint
UPDATE `wp_player_smgs` SET `sticker_2_new` = IF(`sticker_2` = '0;0;0;0;0;0' OR `sticker_2` IS NULL OR CAST(SUBSTRING_INDEX(`sticker_2`, ';', 1) AS SIGNED) = 0, NULL, JSON_OBJECT('id', CAST(SUBSTRING_INDEX(`sticker_2`, ';', 1) AS SIGNED), 'x', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_2`, ';', 2), ';', -1) AS DOUBLE), 'y', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_2`, ';', 3), ';', -1) AS DOUBLE), 'wear', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_2`, ';', 4), ';', -1) AS DOUBLE), 'scale', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_2`, ';', 5), ';', -1) AS DOUBLE), 'rotation', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_2`, ';', 6), ';', -1) AS SIGNED)));--> statement-breakpoint
UPDATE `wp_player_smgs` SET `sticker_3_new` = IF(`sticker_3` = '0;0;0;0;0;0' OR `sticker_3` IS NULL OR CAST(SUBSTRING_INDEX(`sticker_3`, ';', 1) AS SIGNED) = 0, NULL, JSON_OBJECT('id', CAST(SUBSTRING_INDEX(`sticker_3`, ';', 1) AS SIGNED), 'x', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_3`, ';', 2), ';', -1) AS DOUBLE), 'y', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_3`, ';', 3), ';', -1) AS DOUBLE), 'wear', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_3`, ';', 4), ';', -1) AS DOUBLE), 'scale', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_3`, ';', 5), ';', -1) AS DOUBLE), 'rotation', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_3`, ';', 6), ';', -1) AS SIGNED)));--> statement-breakpoint
UPDATE `wp_player_smgs` SET `sticker_4_new` = IF(`sticker_4` = '0;0;0;0;0;0' OR `sticker_4` IS NULL OR CAST(SUBSTRING_INDEX(`sticker_4`, ';', 1) AS SIGNED) = 0, NULL, JSON_OBJECT('id', CAST(SUBSTRING_INDEX(`sticker_4`, ';', 1) AS SIGNED), 'x', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_4`, ';', 2), ';', -1) AS DOUBLE), 'y', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_4`, ';', 3), ';', -1) AS DOUBLE), 'wear', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_4`, ';', 4), ';', -1) AS DOUBLE), 'scale', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_4`, ';', 5), ';', -1) AS DOUBLE), 'rotation', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`sticker_4`, ';', 6), ';', -1) AS SIGNED)));--> statement-breakpoint
UPDATE `wp_player_smgs` SET `keychain_new` = IF(`keychain` = '0;0;0;0;0' OR `keychain` IS NULL OR CAST(SUBSTRING_INDEX(`keychain`, ';', 1) AS SIGNED) = 0, NULL, JSON_OBJECT('id', CAST(SUBSTRING_INDEX(`keychain`, ';', 1) AS SIGNED), 'x', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`keychain`, ';', 2), ';', -1) AS DOUBLE), 'y', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`keychain`, ';', 3), ';', -1) AS DOUBLE), 'z', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`keychain`, ';', 4), ';', -1) AS DOUBLE), 'seed', CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`keychain`, ';', 5), ';', -1) AS SIGNED), 'wrapped_sticker_id', `wrapped_sticker_id`, 'highlight_reel_id', `highlight_reel_id`));--> statement-breakpoint

-- Step 3: Drop old VARCHAR columns
ALTER TABLE `wp_player_heavys` DROP COLUMN `sticker_0`;--> statement-breakpoint
ALTER TABLE `wp_player_heavys` DROP COLUMN `sticker_1`;--> statement-breakpoint
ALTER TABLE `wp_player_heavys` DROP COLUMN `sticker_2`;--> statement-breakpoint
ALTER TABLE `wp_player_heavys` DROP COLUMN `sticker_3`;--> statement-breakpoint
ALTER TABLE `wp_player_heavys` DROP COLUMN `sticker_4`;--> statement-breakpoint
ALTER TABLE `wp_player_heavys` DROP COLUMN `keychain`;--> statement-breakpoint
ALTER TABLE `wp_player_heavys` DROP COLUMN `wrapped_sticker_id`;--> statement-breakpoint
ALTER TABLE `wp_player_heavys` DROP COLUMN `highlight_reel_id`;--> statement-breakpoint
ALTER TABLE `wp_player_pistols` DROP COLUMN `sticker_0`;--> statement-breakpoint
ALTER TABLE `wp_player_pistols` DROP COLUMN `sticker_1`;--> statement-breakpoint
ALTER TABLE `wp_player_pistols` DROP COLUMN `sticker_2`;--> statement-breakpoint
ALTER TABLE `wp_player_pistols` DROP COLUMN `sticker_3`;--> statement-breakpoint
ALTER TABLE `wp_player_pistols` DROP COLUMN `sticker_4`;--> statement-breakpoint
ALTER TABLE `wp_player_pistols` DROP COLUMN `keychain`;--> statement-breakpoint
ALTER TABLE `wp_player_pistols` DROP COLUMN `wrapped_sticker_id`;--> statement-breakpoint
ALTER TABLE `wp_player_pistols` DROP COLUMN `highlight_reel_id`;--> statement-breakpoint
ALTER TABLE `wp_player_rifles` DROP COLUMN `sticker_0`;--> statement-breakpoint
ALTER TABLE `wp_player_rifles` DROP COLUMN `sticker_1`;--> statement-breakpoint
ALTER TABLE `wp_player_rifles` DROP COLUMN `sticker_2`;--> statement-breakpoint
ALTER TABLE `wp_player_rifles` DROP COLUMN `sticker_3`;--> statement-breakpoint
ALTER TABLE `wp_player_rifles` DROP COLUMN `sticker_4`;--> statement-breakpoint
ALTER TABLE `wp_player_rifles` DROP COLUMN `keychain`;--> statement-breakpoint
ALTER TABLE `wp_player_rifles` DROP COLUMN `wrapped_sticker_id`;--> statement-breakpoint
ALTER TABLE `wp_player_rifles` DROP COLUMN `highlight_reel_id`;--> statement-breakpoint
ALTER TABLE `wp_player_smgs` DROP COLUMN `sticker_0`;--> statement-breakpoint
ALTER TABLE `wp_player_smgs` DROP COLUMN `sticker_1`;--> statement-breakpoint
ALTER TABLE `wp_player_smgs` DROP COLUMN `sticker_2`;--> statement-breakpoint
ALTER TABLE `wp_player_smgs` DROP COLUMN `sticker_3`;--> statement-breakpoint
ALTER TABLE `wp_player_smgs` DROP COLUMN `sticker_4`;--> statement-breakpoint
ALTER TABLE `wp_player_smgs` DROP COLUMN `keychain`;--> statement-breakpoint
ALTER TABLE `wp_player_smgs` DROP COLUMN `wrapped_sticker_id`;--> statement-breakpoint
ALTER TABLE `wp_player_smgs` DROP COLUMN `highlight_reel_id`;--> statement-breakpoint

-- Step 4: Rename new JSON columns to original names
ALTER TABLE `wp_player_heavys` CHANGE COLUMN `sticker_0_new` `sticker_0` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_heavys` CHANGE COLUMN `sticker_1_new` `sticker_1` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_heavys` CHANGE COLUMN `sticker_2_new` `sticker_2` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_heavys` CHANGE COLUMN `sticker_3_new` `sticker_3` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_heavys` CHANGE COLUMN `sticker_4_new` `sticker_4` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_heavys` CHANGE COLUMN `keychain_new` `keychain` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_pistols` CHANGE COLUMN `sticker_0_new` `sticker_0` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_pistols` CHANGE COLUMN `sticker_1_new` `sticker_1` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_pistols` CHANGE COLUMN `sticker_2_new` `sticker_2` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_pistols` CHANGE COLUMN `sticker_3_new` `sticker_3` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_pistols` CHANGE COLUMN `sticker_4_new` `sticker_4` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_pistols` CHANGE COLUMN `keychain_new` `keychain` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_rifles` CHANGE COLUMN `sticker_0_new` `sticker_0` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_rifles` CHANGE COLUMN `sticker_1_new` `sticker_1` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_rifles` CHANGE COLUMN `sticker_2_new` `sticker_2` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_rifles` CHANGE COLUMN `sticker_3_new` `sticker_3` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_rifles` CHANGE COLUMN `sticker_4_new` `sticker_4` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_rifles` CHANGE COLUMN `keychain_new` `keychain` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_smgs` CHANGE COLUMN `sticker_0_new` `sticker_0` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_smgs` CHANGE COLUMN `sticker_1_new` `sticker_1` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_smgs` CHANGE COLUMN `sticker_2_new` `sticker_2` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_smgs` CHANGE COLUMN `sticker_3_new` `sticker_3` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_smgs` CHANGE COLUMN `sticker_4_new` `sticker_4` json DEFAULT NULL;--> statement-breakpoint
ALTER TABLE `wp_player_smgs` CHANGE COLUMN `keychain_new` `keychain` json DEFAULT NULL;