name: Deploy VitePress to GH Pages

on:
  push:
    branches:
      - vitepress
      - copilot/vitepress

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sparse checkout only `site/` (partial clone to avoid large blobs)
        # Use raw git to do a partial fetch with blob filtering and a sparse checkout
        # This reduces bandwidth and disk usage by only downloading `site/` files.
        run: |
          git init
          # Authenticate using the runner token so private repos work
          git remote add origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          # Enable sparse-checkout before checking out so we don't populate all files
          git sparse-checkout init --cone
          git sparse-checkout set site
          # Fetch the single commit with blob filtering to avoid downloading large files
          git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 --filter=blob:none origin ${{ github.sha }}
          git checkout -f FETCH_HEAD
        shell: bash

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: site/package-lock.json

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: cd site && npm ci

      - name: Build VitePress site
        run: cd site && npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/.vitepress/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4